### ISSUE TITLE
VoLTE not working while callig someone

### ISSUE THREAD

**Issue by AMDFenics** [zuk-devs/android_device_zuk_z2_row#1]
Hello, i hope i'm right here in this topic. If not, so excuse me please.
I use AEX 5.2 at my ZUK Z2 Pro and the VoLTE isn't working.
Also VoWifi ... I made a call and let a LogCat run, while dial and connect.
[2018-02-23-13-13-41.txt](https://github.com/zuk-devs/android_device_zuk_z2_row/files/1753408/2018-02-23-13-13-41.txt)
Please see attachment for this. Level is "debug". If u need more info, feel free to ask :)

Thanks for your work :)

**Comment by DD3Boh** [comment]
Works in AEX Oreo, and also in AEX Pie with the hax.
